name: Credential Scan

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true  # ❌ fails PR if secrets found
